<?php
/**
 * @file
 * Main file for the Metatag Replace module.
 */

/**
 * Implements hook_permission().
 */
function metatag_replace_permission() {
  return array(
    'metatag_replace' => array(
      'title' => t('Metatag Search'),
      'description' => t('Allow people to search with Metatag Replace'),
    ),
    'metatag_replace_confirm' => array(
      'title' => t('Metatag Replace'),
      'description' => t('Allow people to Replace with Metatag replace'),
    ),
  );
}
/**
 * Implements hook_help().
 */
function metatag_replace_help($path, $arg) {
  switch ($path) {
    case "admin/help#metatag_replace":
      $text = t("<h1>Metatag Replace</h1><p>Metatag Replace is used to either search or replace Meta tags on your site. 
   It Uses Batch API to Read Meta tags and perform operation on them.
   Module supports 4 fields which are provided by <a href='https://www.drupal.org/project/metatag'>Metatag module</a> . 
   This module provides a form for user to search and replace Meta tags. For more Information Please visit the project page
   <a href='https://www.drupal.org/node/2623618'>https://www.drupal.org/node/2623618</a></p>
   <ul>
	 <li>There are options to select particular Content types.</li>
	 <li>Whether we want case sensitive search or not.</li>
	 <li>We can Match Exact Word or not.</li>
	<li>User can choose to select to perform operation Individual Meta Fields or All</li>
	<li>This Modules Creates Revision of each page it changes</li>
  </ul>");
      return $text;
  }
}

/**
 * Implements hook_menu().
 */
function metatag_replace_menu() {
  $items['admin/config/search/metatags/replace'] = array(
    'title callback' => 'Change Metatags',
    'title' => 'MetaTag Replace',
    'description' => 'Replace the MetaTags',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('metatag_replace_form'),
    'access arguments' => array('metatag_replace'),
    'file' => 'metatag_replace_admin.inc',
    'type' => MENU_LOCAL_TASK,
  );

  $items['admin/config/search/metatags/replace/confirm'] = array(
    'title' => 'Confirm Replace',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('metatag_replace_confirm_form'),
    'access arguments' => array('metatag_replace_confirm'),
    'file' => 'metatag_replace_admin.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function metatag_replace_theme() {
  $items = array(
    'metatag_replace_operation_search' => array(
      'variables' => array(
        'list' => array(),
      ),
    ),
    'metatag_replace_operation_replace' => array(
      'variables' => array(
        'list' => array(),
      ),
    ),
  );
  return $items;
}

/**
 * Theme function for search operation.
 *
 * $result['list'] Stores the Following Data
 * $result['list']['search-word']=> Stores the search word.
 * $result['list']['replace-word']=> Stores the replace word.
 * $result['list']['opn']=> Stores operation performed.
 * $result['list']['field_result']=> Stores the Meta field you searched.
 * $result['list']['detail'] => Stores the nid and link of the Node.
 * $result['list'][matches]=> Stores the the array for Metatags found.
 */
function theme_metatag_replace_operation_search($result) {
  if (!empty($result['list']['matches'])) {
    $meta_field = $result['list']['field_result'];
    $title = t('Metatag Replace Result for Search');
    $type = 'ol';
    $attributes = array(
      'id' => 'metatag-replace-result-search',
      'class' => 'metatag-replace-result',
    );
    if ($meta_field != 'all') {
      $search_meta_list = $result['list']['matches'];
      $search_node_link = $result['list']['detail']['node_link'];
      foreach ($search_node_link as $keys => $values) {
        $items[] = array(
          'data' => $values,
          'children' => array(
            'data' => "Meta $meta_field : " . $search_meta_list[$keys],
          ),
        );
      }
    }
    else {
      foreach ($result['list']['matches'] as $keys => $values) {
        $items[] = array(
          'data' => $result['list']['detail'][$keys]['node_link'][0],
          'children' => $values,
        );
      }
    }
    return theme('item_list', array(
      'items' => $items,
      'title' => $title,
      'type' => $type,
      'attributes' => $attributes,
    )
    );
  }
}

/**
 * Theme function for replace operation.
 *
 * $result['list'] Stores the Following Data
 * $result['list']['opn']=> Stores operation state.
 * $result['list']['field_result']=> Stores the Meta field Selected.
 * $result['list']['detail']=> Stores the link to  the Node.
 * $result['list']['replace] => Stores the replaced tags.
 */
function theme_metatag_replace_operation_replace($result) {
  if (!empty($result['list']['detail'])) {
    $meta_field = $result['list']['field_result'];
    $title = t('Metatag Replace Result for Replace');
    $type = 'ol';
    $attributes = array(
      'id' => 'metatag-replace-result-replace',
      'class' => 'metatag-replace-result',
    );
    if ($meta_field != 'all') {
      $replace_meta_list = $result['list']['replace'];
      $replace_node_link = $result['list']['detail']['node_link'];
      foreach ($replace_node_link as $keys => $values) {
        $items[] = array(
          'data' => $values,
          'children' => array(
            'data' => "Meta $meta_field : $replace_meta_list[$keys]",
          ),
        );
      }
    }
    else {
      foreach ($result['list']['replace'] as $keys => $values) {
        $items[] = array(
          'data' => $result['list']['detail'][$keys]['node_link'],
          'children' => $values,
        );
      }
    }
    return theme('item_list', array(
      'items' => $items,
      'title' => $title,
      'type' => $type,
      'attributes' => $attributes,
    )
    );
  }
}
