<?php

/**
 * @file
 * use Drupal's mail API.
 */
 
use Drupal\Component\Utility\SafeMarkup;

function subscribe_newsletter_mail($key, &$message, $params) {
    $message['headers'] = array(
      'MIME-Version' => '1.0',
      'Content-Type' => 'text/html; charset=UTF-8; format=flowed',
      'Content-Transfer-Encoding' => '8Bit',
      'X-Mailer' => 'Drupal'
    );
	$options = array(
      'langcode' => $params['langcode'],
    );
  switch ($key) {
	case 'subscribe_newsletter_form':  
      $from = \Drupal::config('system.site')->get('mail');
	  $message['subject'] = $params['subject'].t(' E-mail sent from @site-name', array('@site-name' => $from), $options);
	  $message['body'][] = SafeMarkup::checkPlain($params['body']);
	  break;
  }
  
}